/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Admin;

import Modelo.CAlumnos;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import Vista.Admin.Admin_Home;


/**
 *
 * @author DELL
 */
public class EditUsers_Admin extends javax.swing.JFrame {

     private String userName;
     private String userDoc;
     private int userRole;
     
     public void setUserDoc(String userDoc){
         this.userDoc = userDoc;
         LbDoc.setText(userDoc);
     }
     
     
     public void setUserName(String userName) {
        this.userName = userName;
        LbNombre.setText(userName);
    }
     
         // Método para establecer el rol del usuario
    public void setUserRole(int userRole) {
        this.userRole = userRole;
        LbRol.setText(userRole == 1 ? "Administrador" : "Usuario");
    }
    
    
    public EditUsers_Admin() {
        
              
        initComponents();
        this.setLocationRelativeTo(null);
        txtId.setEnabled(false);
        txtUser_id.setEnabled(false);
        
//        CConexion objetoConexion = new CConexion();
//        objetoConexion.estableceConexion();

    CAlumnos objetoAlumnos = new CAlumnos();
    objetoAlumnos.MostrarDatosUsuarios(tbTotalAlumnos);
      }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
   private boolean validateTextField(JTextField textField, String fieldName) {
    String text = textField.getText().trim();

    // Validar que el campo no esté vacío
    if (text.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El campo '" + fieldName + "' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validar longitud mínima para nombres
    if (fieldName.equals("Nombres")) {
        if (text.length() < 3) {
            JOptionPane.showMessageDialog(this, "El campo '" + fieldName + "' debe tener al menos 3 caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!text.matches("[a-zA-Z ]+")) {
            JOptionPane.showMessageDialog(this, "El campo '" + fieldName + "' solo puede contener letras.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    // Validar longitud mínima para contraseñas
    if (fieldName.equals("Contrasenia")) {
        if (text.length() < 3) {
            JOptionPane.showMessageDialog(this, "El campo '" + fieldName + "' debe tener al menos 3 caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    // Validación específica para correos electrónicos
    if (fieldName.equals("Correo")) {
        String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        if (!text.matches(emailRegex)) {
            JOptionPane.showMessageDialog(this, "El campo 'Correo' no tiene un formato válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    // Validación para campos que deben contener solo números
    if (fieldName.equals("Doc")) {
        
    // Validar que la cédula solo contenga dígitos
    if (!text.matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this, "La cédula de ciudadanía debe contener exactamente 10 Numeros.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    if (!text.matches("[A-Z0-9]{10,20}")) {
        JOptionPane.showMessageDialog(this, "La cédula de extranjería no tiene un formato válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
        // Suponiendo un formato alfanumérico específico para el PEP
    if (!text.matches("[A-Z0-9]{10,15}")) {
        JOptionPane.showMessageDialog(this, "El Permiso Especial de Permanencia (PEP) no tiene un formato válido.", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    
    }

    // Validación específica para el rol
    if (fieldName.equals("Rol")) {
        if (!text.equals("1") && !text.equals("2")) {
            JOptionPane.showMessageDialog(this, "El campo 'Rol' debe ser 1 (Administrador) o 2 (Usuario).", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    // Implementa validaciones específicas para otros campos si es necesario
    return true;
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDocument = new javax.swing.JTextField();
        txtRol = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUPWD = new javax.swing.JTextField();
        limpiarCampos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUser_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Jc_EstadoUser = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTotalAlumnos = new javax.swing.JTable();
        LbRol = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LbDoc = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                formComponentRemoved(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Usuario"));

        jLabel1.setText("dueño_id");

        jLabel2.setText("Nombres");

        jLabel3.setText("Correo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel4.setText("Documento");

        jLabel5.setText("Rol");

        txtRol.setText("2");

        jLabel6.setText("Contraseña");

        limpiarCampos.setText("Limpiar");
        limpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarCamposActionPerformed(evt);
            }
        });

        jLabel8.setText("Telefono");

        jLabel9.setText("Direccion");

        jLabel10.setText("user_id");

        jLabel11.setText("Estado");

        Jc_EstadoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(limpiarCampos)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser_id, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDocument)
                                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUPWD, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jc_EstadoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombres)
                                        .addComponent(txtTelefono)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtUser_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUPWD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(Jc_EstadoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(27, 27, 27)
                .addComponent(btnModificar)
                .addGap(37, 37, 37)
                .addComponent(limpiarCampos)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Usuarios"));

        tbTotalAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTotalAlumnos.setFocusable(false);
        tbTotalAlumnos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tbTotalAlumnos.getTableHeader().setResizingAllowed(false);
        tbTotalAlumnos.getTableHeader().setReorderingAllowed(false);
        tbTotalAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTotalAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTotalAlumnos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LbRol.setText("Administrador: ");

        LbNombre.setText("Nombre");

        jLabel7.setText("Documento:");

        LbDoc.setText("#");

        btnSalir.setText("Volver");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbRol)
                        .addGap(18, 18, 18)
                        .addComponent(LbNombre)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LbRol)
                                    .addComponent(LbNombre)
                                    .addComponent(jLabel7)
                                    .addComponent(LbDoc))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
 // Obtén el texto de los campos
    // Obtén el texto de los campos
    String user_id = txtUser_id.getText().trim();
    String user_name = txtNombres.getText().trim();
    String upwd = txtUPWD.getText().trim(); // Convierte el password a string y elimina espacios
    String user_email = txtCorreo.getText().trim();
    String user_doc = txtDocument.getText().trim();
    String role_id = txtRol.getText().trim(); // Asigna directamente el número 2 a role_id
    String telefono = txtTelefono.getText().trim();
    String direccion = txtDireccion.getText().trim();
    String estado = (String) Jc_EstadoUser.getSelectedItem(); // Obtén el estado del JComboBox


    // Valida todos los campos necesarios
       if (!validateTextField(txtNombres, "Nombres") ||
        !validateTextField(txtCorreo, "Correo") ||
        !validateTextField(txtDocument, "Doc")||
        !validateTextField(txtRol, "Rol") || 
        !validateTextField(txtUPWD, "Contrasenia")) {
        return; // Si alguna validación falla, no continúa con el guardado
    }

    // Si todas las validaciones pasan, guarda los datos
    CAlumnos objetoAlumno = new CAlumnos();
    objetoAlumno.InsertarAlumno(txtUser_id,txtNombres,txtUPWD,txtCorreo,txtDocument,txtTelefono,txtDireccion,Jc_EstadoUser); // Pasa role_id como parámetro
    objetoAlumno.MostrarDatosUsuarios(tbTotalAlumnos);

    // Limpia los campos de texto
    txtId.setText("");
    txtUser_id.setText("");
    txtNombres.setText("");
    txtTelefono.setText("");
    txtDireccion.setText("");
    txtUPWD.setText("");
    txtCorreo.setText("");
    txtDocument.setText("");
    txtRol.setText("");
    Jc_EstadoUser.setSelectedIndex(-1); // Si quieres que el JComboBox no tenga ninguna selección

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tbTotalAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTotalAlumnosMouseClicked
        // Llama al método SeleccionarAlumno con los parámetros adecuados
    CAlumnos objetoAlumno = new CAlumnos();
    objetoAlumno.SeleccionarAlumno(
        tbTotalAlumnos,
        txtId,          // Campo para ID
        txtUser_id,     // Campo para User ID
        txtNombres,     // Campo para Nombres
        txtTelefono,    // Campo para Teléfono
        txtDireccion,   // Campo para Dirección
        txtCorreo,      // Campo para Correo
        txtDocument,    // Campo para Documento
        txtRol,         // Campo para Rol
        txtUPWD,         // Campo para Contraseña
        Jc_EstadoUser
    );
    }//GEN-LAST:event_tbTotalAlumnosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    // Valida todos los campos necesarios
       if (!validateTextField(txtNombres, "Nombres") ||
        !validateTextField(txtCorreo, "Correo") ||
        !validateTextField(txtDocument, "Doc")||
        !validateTextField(txtRol, "Rol") || 
        !validateTextField(txtUPWD, "Contrasenia")) {
        return; // Si alguna validación falla, no continúa con el guardado
    }
    
    // Si todas las validaciones pasan, modifica los datos
    CAlumnos objetoAlumno = new CAlumnos();
    objetoAlumno.ModificarAlumnos(txtId,txtUser_id,txtNombres,txtTelefono,txtDireccion,txtCorreo,txtDocument,txtRol,txtUPWD,Jc_EstadoUser);
    objetoAlumno.MostrarDatosUsuarios(tbTotalAlumnos);

    // Limpia los campos de texto
    txtId.setText("");
    txtUser_id.setText("");
    txtNombres.setText("");
    txtTelefono.setText("");
    txtDireccion.setText("");
    txtUPWD.setText("");
    txtCorreo.setText("");
    txtDocument.setText("");
    txtRol.setText("");
    Jc_EstadoUser.setSelectedIndex(-1); // Si quieres que el JComboBox no tenga ninguna selección

    }//GEN-LAST:event_btnModificarActionPerformed

    private void limpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarCamposActionPerformed
        // TODO add your handling code here:
    // Limpia los campos de texto
    txtId.setText("");
    txtUser_id.setText("");
    txtNombres.setText("");
    txtTelefono.setText("");
    txtDireccion.setText("");
    txtUPWD.setText("");
    txtCorreo.setText("");
    txtDocument.setText("");
    txtRol.setText("");
    Jc_EstadoUser.setSelectedIndex(-1); // Si quieres que el JComboBox no tenga ninguna selección
    }//GEN-LAST:event_limpiarCamposActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         // Cierra la ventana actual
        this.dispose();
        // Muestra la ventana de login
        Vista.Admin.Admin_Home loginWindow = new Vista.Admin.Admin_Home();
        loginWindow.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUsers_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUsers_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUsers_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUsers_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista.Admin.EditUsers_Admin().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jc_EstadoUser;
    private javax.swing.JLabel LbDoc;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JLabel LbRol;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarCampos;
    private javax.swing.JTable tbTotalAlumnos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocument;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRol;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUPWD;
    private javax.swing.JTextField txtUser_id;
    // End of variables declaration//GEN-END:variables
}
