package Vista.Usuario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import Modelo.CAlumnos;
import Vista.Usuario.Historia_Clinica;
import javax.swing.JOptionPane;
import Modelo.Controladora_logica;
import Vista.Usuario.Editar_Usuario;
import Vista.Usuario.Vacunas;

/**
 *
 * @author DELL
 */
public class HomeUser extends javax.swing.JFrame {
    
            Controladora_logica controladora = new Controladora_logica();

    private String userName;
    private String userDoc;
    private String nombre;


    public void setUserDoc(String userDoc){
        this.userDoc = userDoc;
        txtDoc.setText(userDoc);
        cargarDatosMascotas(this.userDoc); // Llamar al método para cargar los datos de mascotas
        nombre = controladora.getUserName(userDoc);
        txtAdmin1.setText(nombre);
    }

    public HomeUser() {
        initComponents();    
        this.setLocationRelativeTo(null);
        txtMascota_Select.setEnabled(false);
        
        
    }
    
    
    
    
    

    public void cargarDatosMascotas(String userDoc1) {        
        CAlumnos objetoAlumnos = new CAlumnos();
        objetoAlumnos.MostrarDatosMascotas(TbMascotas, this.userDoc);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAdmin1 = new javax.swing.JLabel();
        txtDoc = new javax.swing.JLabel();
        btnConfigUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbMascotas = new javax.swing.JTable();
        btnVacunas = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnHistoria_Clinica = new javax.swing.JButton();
        txtMascota_Select = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 219, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Usuario"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("USUARIO");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N

        txtAdmin1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAdmin1.setText("                                                 ");

        txtDoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDoc.setText("                   ");

        btnConfigUser.setBackground(new java.awt.Color(204, 219, 255));
        btnConfigUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfigUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/config.png"))); // NOI18N
        btnConfigUser.setText("Configuracion");
        btnConfigUser.setBorder(null);
        btnConfigUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfigUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConfigUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfigUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(txtAdmin1)
                        .addComponent(txtDoc))
                    .addComponent(btnConfigUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(txtAdmin1)
                .addGap(26, 26, 26)
                .addComponent(txtDoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnConfigUser)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mascotas"));

        TbMascotas.setBackground(new java.awt.Color(204, 204, 204));
        TbMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TbMascotas.setFocusable(false);
        TbMascotas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TbMascotas.getTableHeader().setResizingAllowed(false);
        TbMascotas.getTableHeader().setReorderingAllowed(false);
        TbMascotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbMascotasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbMascotas);

        btnVacunas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVacunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vacunas.png"))); // NOI18N
        btnVacunas.setText("Ver Vacunas");
        btnVacunas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVacunas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnVacunas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacunasActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Seguro.png"))); // NOI18N
        jButton2.setText("Ver Seguros");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnHistoria_Clinica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHistoria_Clinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Historia Clinica.png"))); // NOI18N
        btnHistoria_Clinica.setText("Ver Historia Clinica");
        btnHistoria_Clinica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistoria_Clinica.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHistoria_Clinica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHistoria_Clinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoria_ClinicaActionPerformed(evt);
            }
        });

        txtMascota_Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMascota_SelectActionPerformed(evt);
            }
        });

        jLabel3.setText("Mascota Seleccionada");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txtMascota_Select, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(91, 91, 91)
                        .addComponent(btnVacunas)
                        .addGap(67, 67, 67)
                        .addComponent(btnHistoria_Clinica)
                        .addGap(67, 67, 67)
                        .addComponent(jButton2)
                        .addGap(91, 91, 91)
                        .addComponent(btnSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHistoria_Clinica)
                            .addComponent(btnVacunas)
                            .addComponent(jButton2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtMascota_Select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnSalir)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoria_ClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoria_ClinicaActionPerformed
        // TODO add your handling code here:
        
                // TODO add your handling code here:
        // Obtén el texto de los campos
    // Obtén el texto de los campos
    String nombrePet = txtMascota_Select.getText().trim();
    String user_doc = userDoc;
    String UserName = userName;
    
     if (nombrePet.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El campo Selecciona Mascota no puede estar vacío, Por favor Selecciona una Mascota.");
    }else{
     
      JOptionPane.showMessageDialog(this, "Bienvenido a Vacunas", "Éxito", JOptionPane.INFORMATION_MESSAGE);
             // Abre la vista de HomeUser y pasa el nombre, rol y documento
            Historia_Clinica formAdmin = new Historia_Clinica();
            formAdmin.setPetName(nombrePet);
            formAdmin.setUserName(userName);
            formAdmin.setUserDoc(userDoc);
            formAdmin.setVisible(true);
            this.dispose(); // Cierra la ventana de login

     }



       
    }//GEN-LAST:event_btnHistoria_ClinicaActionPerformed

    private void txtMascota_SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMascota_SelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMascota_SelectActionPerformed

    private void TbMascotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbMascotasMouseClicked
        // TODO add your handling code here:
    CAlumnos objetoAlumno = new CAlumnos();
    objetoAlumno.SeleccionarMascota_User(
        TbMascotas,
        txtMascota_Select // Campo para ID
    );
       
    }//GEN-LAST:event_TbMascotasMouseClicked

    private void btnVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacunasActionPerformed
   
    String nombrePet = txtMascota_Select.getText().trim();
    String user_doc = userDoc;
    String UserName = userName;
    
     if (nombrePet.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El campo Mascota Seleccionada no puede estar vacío, Por favor Selecciona una Mascota.");
    }else{
     
            Vacunas formAdmin = new Vacunas();
            formAdmin.setPetName(nombrePet);
            formAdmin.setUserName(userName);
            formAdmin.setUserDoc(userDoc);
            formAdmin.setVisible(true);
            this.dispose(); // Cierra la ventana de login

     }



    }//GEN-LAST:event_btnVacunasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
                 // Cierra la ventana actual
        this.dispose();
        // Muestra la ventana de login
        Vista.Login loginWindow = new Vista.Login();
        loginWindow.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConfigUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigUserActionPerformed
        // TODO add your handling code here:
            String documento = userDoc;
            
           int user_id = controladora.getUserID(userDoc);
           String pass = controladora.ValidatePassword(userDoc);
           String email = controladora.getUserEmail(userDoc);
           String Address = controladora.getUserAddress(userDoc);
           String Phone = controladora.getUserPhone(userDoc);
        
            Editar_Usuario formAdmin = new Editar_Usuario();
            formAdmin.setUser_ID(user_id);
            formAdmin.setDocUser(documento);
            formAdmin.setNombreUser(userName);
            formAdmin.setEmailUser(email);
            formAdmin.setAdressUser(Address);
            formAdmin.setPhoneUser(Phone);
            formAdmin.setpass(pass);
            formAdmin.setVisible(true);
            this.dispose(); // Cierra la ventana de login

    }//GEN-LAST:event_btnConfigUserActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbMascotas;
    private javax.swing.JButton btnConfigUser;
    private javax.swing.JButton btnHistoria_Clinica;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVacunas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtAdmin1;
    private javax.swing.JLabel txtDoc;
    private javax.swing.JTextField txtMascota_Select;
    // End of variables declaration//GEN-END:variables
}
